obj-$(CONFIG_LGE_DISPLAY_JOAN_COMMON) += joan/
obj-$(CONFIG_LGE_DISPLAY_PHOENIX_COMMON) += phoenix/


obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_dsi.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_dsi_panel.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_fb.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += lge_mdss_sysfs.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += notifier/lge_panel_notifier.o
obj-$(CONFIG_LGE_DISPLAY_COMMON) += ambient/lge_ambient.o
obj-$(CONFIG_LGE_INTERVAL_MONITOR) += lge_interval_monitor.o
obj-$(CONFIG_LGE_FBCN) += lge_fbcn.o
