#
# Makefile for nfc devices
#

obj-$(CONFIG_LGE_NFC_PN553)             += pn553_lge.o
obj-$(CONFIG_LGE_NFC_PN553)             += pn553_lge_hwadapter.o
ccflags-$(CONFIG_NFC_DEBUG)             := -DDEBUG

